### PR TITLE
🎨 Admin++

### PR DESCRIPTION
**Pull request by jycouet**

### CODE REVIEW

**Comment by jycouet** [comment]
I don't manage to find existing tests for admin part. You can advice @noam-honig ?

**Comment by noam-honig** [comment]
There are none at this time

**Comment by jycouet** [comment]
I'm not sure what to add :o
Actually, I don't get how they are counting it :/

**Comment by noam-honig** [comment]
The coverage is counted by code that runs as part of the "npm run test" code - in that process. anything else is not included in coverage

To conver things, I usually add tests within the regular tests of what can be covered.

As for the decrease in coverage - don't worry, since pull requests can't run the mongo db tests due to environment variables - that is the cause of the decrease in coverage

**Comment by jycouet** [comment]
Good, so good to merge? :D

In next PR, you want me to look at mongo ?

**Comment by noam-honig** [comment]
The issue with mongo is:
1. there are tests that are done with docker - but that version doesn't support transactions.
2. there are tests that are done with atlas - but that has a database url that is a secret and is not included in the ci of prs.
3.

**Comment by noam-honig** [comment]
@jycouet Are you ok with merging this?

**Comment by jycouet** [comment]
Yes, we can

**Pull request merged**
