### PR TITLE
318 support array of dbid in mongo data provider

### PR DESCRIPTION
**Pull request by itamardavidyan**
issue #318

### CODE REVIEW

**Comment by noam-honig** [comment]
I prepared a solution that doesn't require changes inside remult, can you checkout the sandbox link added to the issue and let me know what you think?

**Comment by itamardavidyan** [comment]
> can you checkout the sandbox link added to the issue

I can't found the link
Can you add the link here please?

**Comment by noam-honig** [comment]
Sorry - I wrote a complete answer in the issue and probably forgot to click send - here it is:

Sorry about that - I wrote a long complete answer and probably forgot to send it.

Here's a link to a codesandbox that shows how you can do that in your code:
https://codesandbox.io/p/devbox/mongodb-objectid-array-storage-j698q7


Here's the entity code:
```ts
import { Entity, Fields } from "remult";
import { ObjectId } from "mongodb";

@Entity("tasks", {})
export class task {
  @Fields.string({
    valueConverter: {
      fieldTypeInDb: "dbid",
    },
    dbName: "_id",
  })
  id = "";
  @Fields.string()
  title = "";
  @Fields.string({
    allowNull: true,
    valueConverter: {
      toDb: (val) =>
        val ? new ObjectId(val) : val === null ? null : undefined,
      fromDb: (val) =>
        val ? val.toHexString() : val === null ? null : undefined,
    },
  })
  parentId: string | null = null;
  @Fields.json<task, string[]>({
    allowNull: true,
    valueConverter: {
      toDb: (val) => val?.map((val) => new ObjectId(val)) || null,
      fromDb: (val) => val?.map((val: ObjectId) => val.toHexString()) || null,
    },
  })
  childrenIds: string[] | null = null;
}

```


I also instructed vite (my bundler) to not load `mongodb` to the frontend in the vite.config
```ts
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { stripper } from "vite-plugin-stripper";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    stripper({ decorators: ["BackendMethod"], packages: ["mongodb"] }),
  ],
  server: { proxy: { "/api": "http://localhost:3002" } },
});

```

**Comment by noam-honig** [comment]
solution provided outside this pr

**Pull request closed without merging**
