### PR TITLE
migrate to remult kit

### PR DESCRIPTION
**Pull request by Yedidyar**

### CODE REVIEW

**Comment by Yedidyar** [comment]
Very much I already used it 😄
But I miss the `index.ts` file with the entities

**Comment by jycouet** [comment]
Should be back soon 😊

**Comment by Yedidyar** [comment]
I also think that some tests around the generation of the files are a must

**Comment by noam-honig** [comment]
There are several in:
https://github.com/noam-honig/remult-kit/blob/main/src/lib/cli/getEntity.test.ts

What do you feel is missing?

**Comment by Yedidyar** [comment]
Oh i missed it. never mind

**Pull request merged**
