### PR TITLE
Having 2 cols looking at the same field

### PR DESCRIPTION
**Pull request by jycouet**
This is to enable: 

```ts
@Fields.number({ dbName: 'siteId' })
siteId: number
@Field(() => Site, { dbName: 'siteId' })
site: Site
```

_(⚠️ Has to be merged after the [jycouet:fix/schema-builder](https://github.com/jycouet/remult/tree/fix/schema-builder) one as it's based on it)_

### CODE REVIEW

**Comment by noam-honig** [comment]
This should run with tests on all databases - see tests at:
https://github.com/noam-honig/cfp-list/blob/master/src/server/postgres-with-schema.ts#L41

(Yes I need house keeping)

to run these tests:
npm run server-test

**Review by noam-honig — CHANGES_REQUESTED** [review]
This should run with tests on all databases - see tests at:
https://github.com/noam-honig/cfp-list/blob/master/src/server/postgres-with-schema.ts#L41

(Yes I need house keeping)

to run these tests:
npm run server-test

**Comment by jycouet** [comment]
I'll have a look 👍

**Comment by jycouet** [comment]
I'll close this one as you can get the id with
```ts
id = remult.repo(Task).getEntityRef(item).fields.category.getId();
```

And userland, you can reduce it with
```ts
idOf(Task, item).category.getId()

const idOf = <T>(entity: ClassType<T>, item: T) => {
  return remult.repo(entity).getEntityRef(item).fields;
};
```

**Pull request closed without merging**
