### PR TITLE
:pencil2: UPDATE: Sveltekit demo & init doc/tuto

### PR DESCRIPTION
**Pull request by jycouet**

### CODE REVIEW

**Comment by noam-honig** [comment]
This looks good, but there are still a lot of 🚧 Under construction 🚧

Is it ready for merge?

**Comment by jycouet** [comment]
I think so yes. It's to have at least the clone part ✌️

**Comment by noam-honig** [comment]
> I think so yes. It's to have at least the clone part ✌️

And all the unfinished articles will be published as under construction? or have you done something else?

**Comment by jycouet** [comment]
I wanted to remove all "empty" pages, but it's probably good to keep the same structure for all tutorials.
That's why I added all these "🚧 Under construction 🚧". (quick and dirty solution?)

Unfortunatly, no, I don't have something else _(and I will not do it in the coming few days)_.
I do think it's better than absolutly 0. It can also wait a bit more content maybe?

You decide 👍:D

**Comment by noam-honig** [comment]
@yoni-rapoport Would love your feedback on this

**Comment by jycouet** [comment]
I close this one in favor of the new updated one

**Pull request closed without merging**
